version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
- package-ecosystem: pip
  directory: "/."
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-name: pip
  - dependency-name: click
  - dependency-name: attrs
