language: python
sudo: false
matrix:
  include:
  - python: "3.5"
    env: TEST_TYPE=typecheck
  - python: "2.7"
    env: TEST_TYPE=test
  - python: "2.7"
    env: TEST_TYPE=check
install:
  - pip install -e .
  - travis_retry pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then pip install mypy-lang==0.4.5; fi
script:
  - make $TEST_TYPE
after_success:
  - codecov